### ISSUE TITLE
Week 38 - juggernaut

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#193]
## Terminal Stuff

* [x] `$ brew upgrade bat fzf git heroku hokusai hub macvim the_silver_searcher tmux yarn`
* [x] `$ replug`
* [x] `$ asdf update && asdf plugin-update --all && asdf reshim`
* [x] `$ gem update --system`
* [x] `$ npm install -g npm`
* [x] `$ nuke_modules`

## Filesystem Housekeeping

* [x] cleanup desktop
* [x] cleanup screenshots
* [x] cleanup screen captures
* [x] cleanup downloads
* [x] empty trash

## Check for Updates

* [x] Alfred
* [x] iTerm2
* [x] 1Password
* [x] Figma
* [x] [Xcode][]
* [x] do App Store.app updates
* [x] do System Updates

## Stay in Sync

* [x] push/pull changes on dotfiles
* [x] push/pull changes on notes
* [x] push/pull changes on secrets
* [x] update list of Artsy repos

## Finishing Up

* [x] check free disk space
* [x] verify last backup on time machine
* [x] reboot

[Xcode]: https://developer.apple.com/download/more/

**Comment by jonallured** [comment]
## sharpen.log

<details>

```
+ brew upgrade asdf bat fzf gh git heroku hokusai httpie hub macvim the_silver_searcher tmux yarn zsh-completions
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 5 taps (homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/services and mongodb/brew).
==> New Formulae
alsa-lib
infracost
ladspa-sdk
libirecovery
libseccomp
prometheus-cpp
vtk@8.2
==> Updated Formulae
Updated 297 formulae.
==> New Casks
ajour
dropbox-passwords
duoshao
medibangpaintpro
mic-drop
==> Updated Casks
0xed
1password
1password-cli
4k-video-downloader
a-better-finder-attributes
a-better-finder-rename
ableton-live
ableton-live-lite
ableton-live-suite
abricotine
abstract
accurics
ace-link
acorn
acronis-true-image
activedock
activitywatch
adguard
adium
adobe-digital-editions
adobe-dng-converter
aegisub
aerial
agenda
aimersoft-video-converter-ultimate
air-video-server-hd
aircall
airdroid
airflow
airfoil
airparrot
airpass
airserver
airtable
airunlock
airy
alacritty
aleph-one
alinof-timer
all-in-one-messenger
alt-tab
altair-graphql-client
alva
amadeus-pro
amadine
amazon-music
amazon-photos
amethyst
amitv87-pip
amm
amorphousdiskmark
ananas-analytics-desktop-edition
android-file-transfer
android-messages
android-studio
android-studio-preview-canary
androidtool
angry-ip-scanner
anka-flow
anki
another-redis-desktop-manager
anybar
anydesk
anydo
anytrans
ao
apk-icon-editor
app-tamer
appdelete
appgrid
apple-events
apple-juice
applepi-baker
apppolice
appzapper
aquamacs
archipelago
archiver
arduino
aria2d
aria2gui
ariang
ark-desktop-wallet
armory
arq
artisan
ascension
asciidocfx
astropad
atext
atom
atom-beta
au-lab
audio-hijack
audioscrobbler
audirvana
augur
auristor-client
aurora-hdr
auryo
authy
autodmg
automute
autopkgr
autovolume
avibrazil-rdm
avidemux
avira-antivirus
avitools
aws-vault
axe-edit-iii
axe-electrum
axure-rp
backuploupe
badlion-client
baidunetdisk
balenaetcher
ballast
balsamiq-wireframes
bandage
banking-4
banktivity
baritone
barrier
bartender
barxtemp
base
basictex
batchmod
bbedit
bdash
beacon-scanner
beaker-browser
beamer
beekeeper-studio
beoplay-software-update
betaflight-configurator
bettertouchtool
betterzip
betwixt
beyond-compare
bibdesk
big-mean-folder-machine
bilibili
birdfont
biscuit
bisq
bit-slicer
bitbar
bitshares
bitwarden
blink1control
blocs
bloodhound
bloomrpc
blooo
blu-ray-player
blu-ray-player-pro
bluestacks
blurred
boinc
bookends
boom
boom-3d
boop
boostnote
bootxchanger
box-sync
boxcryptor
boxer
boxofsnoo-fairmount
brackets
brainfm
brave-browser
brave-browser-beta
brave-browser-dev
breaktimer
bria
brightness-sync
brisk
brisync
brook
browserosaurus
btcpayserver-vault
bunch
burn
busycal
busycontacts
butter
buttercup
bzflag
cabal
caffeine
cakebrew
calendar-366
calibre
camera-live
candybar
cantata
caprine
caption
capto
carbon-copy-cloner
cardhop
ccmenu
cd-to
cellprofiler
cerebro
chai
charles
chatmate-for-whatsapp
chatology
cheatsheet
chiaki
chirp
chromium
chronicle
chronosync
chrysalis
cinch
cisdem-document-reader
cisdem-pdf-converter-ocr
cityofzion-neon
ckb-next
clamxav
clash-for-windows
clashx
clashxr
classroom-assistant
clean-me
cleanmymac
cleanshot
cleartext
clementine
clipgrab
clipy
clock-bar
clockify
cloudapp
cloudmounter
cloudytabs
coccinellida
cockatrice
cocktail
cocoarestclient
coconutbattery
coconutid
coda
codekit
codelite
coderunner
colorsnapper
commander-one
comparemerge
conferences
container-ps
contexts
cookie
copyq
cord
corona-tracker
coteditor
couchpotato
cpuinfo
criptext
crossover
crunch
crypter
cryptomator
cryptr
cubicsdr
cumulus
curio
cyberduck
cytoscape
daedalus
daisydisk
darktable
dash
dash-dash
dashlane
dat
data-rescue
datweatherdoe
db-browser-for-sqlite
dbeaver-community
dbglass
dbvisualizer
deco
deeper
deepl
deezer
default-folder-x
deltawalker
deluge
detectx-swift
devdocs
devolo-cockpit
devonagent
devonthink
dexed
dictunifier
diffmerge
dingtalk
disablemonitor
discord
discord-canary
discord-ptb
discretescroll
disk-drill
disk-inventory-x
diskcatalogmaker
diskmaker-x
diskwave
divvy
djay-pro
dmm-player
do-not-disturb
docker
docker-edge
dogecoin
dolphin
dosbox-x
dotnet-preview
downie
dozer
dragthing
drawbot
drivedx
drop-to-gif
dropbox-beta
dropdmg
dropletmanager
dropshare
duckietv
duet
dungeon-crawl-stone-soup-console
dungeon-crawl-stone-soup-tiles
dupeguru
duplicati
dynamic-dark-mode
dynobase
easy-move-plus-resize
easyfind
eddie
electerm
electric-sheep
electrocrud
electron
electron-api-demos
electron-cash
electron-fiddle
electronmail
electrum
electrumsv
element
elmedia-player
eloston-chromium
elpass
emacsclient
emclient
eme
encryptme
endless-sky
enpass
envkey
epic-games
epichrome
eqmac
espresso
ethereum-wallet
etrecheckpro
evernote
exfalso
exifrenamer
exist-db
exodus
expandrive
explorer
expressions
expressvpn
extraterm
falcon-sql-client
fantastical
fastrawviewer
fastscripts
faxbot
fedora-media-writer
feishu
fenix
ferdi
fetch
ff-works
fiji
file-juicer
filebot
filedrop
filepane
find-any-file
findergo
finereader
finicky
firefox
fireworks
fission
fitbit-os-simulator
flame
flash-player
flash-player-debugger
fldigi
flipper
flixtools
flock
flotato
flowsync
fluid
flume
flux
flycut
fog
folding-at-home
folx
fontexplorer-x-pro
fontgoggles
fontlab
fontplop
fork
forklift
foxitreader
foxmail
fraise
framer
freac
free-download-manager
free-ruler
freemind
freenettray
freeze
frescobaldi
fromscratch
fsnotes
funter
fuse
futuniuniu
fuwari
ganache
garagebuy
gargoyle
gas-mask
gb-studio
gcollazo-mongodb
gdlauncher
geany
geekbench
geektool
gemini
geogebra
geotag
gephi
get-backup-pro
get-lyrical
getrasplex
gifox
gifrocket
gifs
gimp
gisto
git-it
gitee
gitfinder
gitfox
github
gitify
gitkraken
glance
glyphs
gmail-notifier
gns3
gnucash
go-agent
go-server
go64
gog-galaxy
goldencheetah
goodsync
goofy
google-chat
google-earth-pro
gopass-ui
gpodder
gpower
gqrx
grammarly
gramps
grandperspective
grandtotal
graphicconverter
graphiql
graphql-ide
graphsketcher
gray
gridea
grids
guijs
guppy
gzdoom
ha-menu
hacker-menu
hackintool
hammerspoon
hand-mirror
handbrake
hands-off
handshaker
handylock
harbor
harvest
hazeover
headset
heaven
helium
hex-fiend
hiddenbar
hocus-focus
home-inventory
honer
hookshot
horos
hotswitch
houdahspot
houseparty
hstracker
hue-topia
hugin
hwsensors
hype
hyper
ibettercharge
ibm-cloud-cli
icab
icanhazshortcut
icloud-control
icollections
icons
icons8
icq
idefrag
iexplorer
ifunbox
igdm
iglance
iina
iina-plus
image2icon
imagealpha
imageoptim
imazing
impactor
inav-configurator
inboard
inform
inkdrop
inkscape
inky
insomnia
insomnia-designer
install-disk-creator
integrity
intel-power-gadget
intellij-idea-ce
intune-company-portal
invisiblix
ip-in-menu-bar
ipartition
ipfs
iphoto-library-manager
iris
isimulator
istat-menus
istat-server
istumbler
isyncr
iterm2
iterm2-beta
itrash
itsycal
itubedownloader
ivideonclient
ivolume
izip
jalbum
james
jamf-migrator
jami
jamovi
jasper
java
jbrowse
jd-gui
jedit-omega
jeromelebel-mongohub
jetbrains-toolbox
jettison
jewelrybox
jgrasp
jitsi-meet
jmc
joshjon-nocturnal
journey
jsui
jubler
juicebar
julia
jump
jumpcut
jumpshare
jupyter-notebook-viewer
kactus
kakapo
kaleidoscope
kap
karabiner-elements
katalon-studio
katana
kawa
keep
keep-it
keepassx
keepassxc
keepingyouawake
keeweb
keka
kekadefaultapp
kern
kext-updater
kextviewr
keybase
keyboardcleantool
keycast
keycastr
keycue
keypad-layout
keysmith
kid3
kindle
kindle-comic-converter
kitematic
kitty
kiwix
kmbmpdc
knockknock
knuff
koa11y
kodi
koodo-reader
krita
kubecontext
kui
kvirc
lab
laravel-kit
lark
lastfm
lastpass
latest
latexit
launchbar
launchcontrol
launchpad-manager
lektor
lens
leocad
lepton
libreoffice
libreoffice-language-pack
libreoffice-still
licecap
lidarr
lighting
lightproxy
lighttable
lincastor
linear
linear-linear
lingo
lingon-x
linkliar
listen1
litecoin
liteicon
liteide
little-snitch
lmms
loaf
lockrattler
loom
loopback
losslesscut
lrtimelapse
lulu
lumen
lunar
luxmark
luyten
lyricsx
macclean
maccy
macdown
macdropany
macgesture
machoexplorer
macintoshjs
macjournal
macpar-deluxe
macpass
macpilot
macs-fan-control
mactracker
macvim
macwinzipper
macx-dvd-ripper-pro
macx-video-converter-pro
macx-youtube-downloader
magiccap
mailbutler
mailmate
mailspring
maintenance
makemkv
malwarebytes
mamp
manico
manictime
manta
marathon
marginnote
maria
marked
markright
marsedit
marvin
masscode
masterway-note
mate-translate
mattermost
mavensmate
max
mcgimp
mdrp
media-center
mediaelch
mediahuman-audio-converter
mediahuman-youtube-downloader
meetingbar
megasync
meld
mellow
mellowplayer
mendeley
mendeley-reference-manager
menubar-colors
menubar-countdown
menubar-stats
menutube
merlin-project
meshlab
meshmixer
messenger-native
meta
metabase
metasploit
metaz
meteorologist
mgba
mia-for-gmail
michaelvillar-timer
micro-snitch
microsoft-edge
microsoft-edge-beta
microsoft-edge-dev
microsoft-outlook
middle
miditrail
milanote
milkytracker
min
mindforger
mindjet-mindmanager
minitube
missive
mist
mixxx
mjml
mjolnir
mkchromecast
mkvtoolnix
mkvtools
mmex
mobster
mochi
mockoon
modmove
modulair
mojibar
molotov
monal
monero-wallet
moneydance
moneymoney
moneywiz
mongotron
monitorcontrol
monodraw
monogame
monolingual
moom
moonlight
morkro-papyrus
mos
mosaic
motrix
mountain-duck
mounty
movist
movist-pro
mp4tools
mpeg-streamclip
mplayer-osx-extended
mplayerx
mps
mu-editor
mucommander
mudlet
mullvadvpn
multitouch
mumble
murus
muse
museeks
musescore
musicbrainz-picard
musictube
mweb
my-budget
mycloud
mymonero
mysqlworkbench
nagbar
nally
name-mangler
namebench
namechanger
nano
natron
navicat-for-mariadb
navicat-for-mysql
navicat-for-oracle
navicat-for-sqlite
ndm
near-lock
neofinder
netbeans
netdownloadhelpercoapp
neteasemusic
netnewswire
netron
netspot
network-radar
nextcloud
nfov
nheko
night-owl
nightfall
nightingale
nightowl
nimble-commander
nimbus
nisus-thesaurus
nitroshare
no-ip-duc
nocturnal
nocturne
nodebox
noisy
nordvpn
nordvpn-teams
nosleep
notable
noti
notion
novabench
now
noxappplayer
nozbe
nrlquaker-winbox
nslogger
nteract
nuclear
nulloy
nullpomino
numi
nvalt
nvidia-geforce-now
nzbget
nzbvortex
obs
obsidian
obyte
odrive
omnidb
omnidisksweeper
omnifocus
omnioutliner
omniplan
omnipresence
ondesoft-audiobook-converter
one-switch
onedrive
oni
onionshare
onlyoffice
onyx
open-ecard
open-in-code
openaudible
openconnect-gui
opencpn
opendnsupdater
openemu
openineditor-lite
openinterminal
openinterminal-lite
openkey
openmsx
openmw
openoffice
openpht
openra
openrct2
openscad
opensesame
opensim
opentoonz
openwebstart
opera
opera-beta
opera-developer
oracle-jdk
oracle-jdk-javadoc
oryoki
osu-development
otx
outline
outline-manager
overkill
oversight
owncloud
packet-peeper
packetproxy
packetsender
pagico
paintbrush
panda
pandora
panic-unison
paparazzi
paperspace
paragon-vmdk-mounter
parallels
parallels-toolbox
parallels-virtualization-sdk
paraview
pastebot
path-finder
paw
pd-l2ork
pdf-expert
pdf-squeezer
pdfelement
pdfpen
pdfpenpro
pdfsam-basic
pdfshaver
peakhour
penc
pencil
pencil2d
permute
persepolis-download-manager
pext
phoneclean
phonegap
phonerescue
photoninja
photosweeper-x
photozoom-pro
pibakery
picgo
piezo
pingmenu
pingplotter
pinta
pixelsnap
pixelstick
platypus
playback
playmemories-home
playonmac
plex
plex-media-player
plex-media-server
plexamp
pliim
plistedit-pro
plover
plug
pngyu
pock
pocket-casts
podcastmenu
podolski
poi
pomolectron
pomotroid
popchar
popclip
popo
porting-kit
postbird
postbox
postico
postman
power-manager
powerphotos
powershell
powershell-preview
powershell6
praat
preform
prefs-editor
printopia
pritunl
prizmo
proclaim
progressive-downloader
protonmail-unofficial
protonvpn
proxyman
prusaslicer
psychopy
pullover
puppetry
pycharm
pycharm-ce
pycharm-edu
pyfa
qbittorrent
qdesktop
qfinder-pro
qgis
qgroundcontrol
qiyimedia
qlcolorcode
qmoji
qownnotes
qq
qqlive
qqmusic
qqplayer
qr-journal
qsyncthingtray
qt-design-studio
qtpass
qtum
quail
quassel
quassel-client
quaternion
quicken
quickhue
quicksilver
quicksync
quik
quip
quiterss
quitter
quodlibet
qutebrowser
qyooo
r
radarr
radiant-player
radio-silence
rambox
ramme
rapidweaver
raven
raven-reader
rawtherapee
rcloneosx
react-proto
reactotron
realm-studio
reaper
refined-github-safari
reflector
reggy
reikey
rekordbox
remote-desktop-manager
remote-desktop-manager-free
renamer
rescuetime
resilio-sync
responsively
reveal
ricochet
rider
rightfont
ring
ringcentral
ripit
river-sparkle
robo-3t
roboform
rocket
rocks-n-diamonds
rodeo
roon
rowanj-gitx
rstudio
rstudio-preview
rsyncosx
runjs
safari-technology-preview
sameboy
scap-workbench
scapple
schism-tracker
scihubeva
scilab
scout
scratch
screen
screenflick
screenflow
screenfocus
screens
screens-connect
scribus
scrivener
scroll-reverser
scrooo
sdformatter
seadrive
seamonkey
seashore
securityspy
selfcontrol
send-anywhere
send-to-kindle
sensei
senuti
sequel-pro
sequential
serial
servpane
session
sessionrestore
sf-symbols
shadowsocksx
shadowsocksx-ng-r
shellhere
shiba
shift
shiftit
shifty
shimeike-formulatepro
shimo
shortcutdetective
shotcut
showyedge
shutter-encoder
sia-ui
sidenotes
sigil
signal
signal-beta
silentknight
sim-daltonism
simple-comic
simplecap
simsim
sip
sizeup
sizzy
sketch
sketchbook
sketchup-pro
skim
skitch
skyfonts
skype
skype-for-business
slate
slimhud
slingplayer
sloth
smart-converter-pro
smcfancontrol
snagit
snapndrag
snowflake-snowsql
snwe
soda-player
softmaker-freeoffice
softu2f
sonarr-menu
sonic-pi
soulver
soundcloud-downloader
soundflowerbed
soundsource
sourcetrail
sourcetree
spaceradar
spamsieve
sparkleshare
spechtlite
spectacle
spectacle-editor
spectrum
spectx
spek
splayer
spotifree
spotmenu
spotspot
springtoolsuite
sqlitemanager
sqlitestudio
sqlpro-for-mssql
sqlpro-for-mysql
sqlpro-for-postgres
sqlpro-for-sqlite
sqlpro-studio
ssh-config-editor
stack
stack-stack
standard-notes
startupizer
stats
statusfy
stay
steermouse
stella
stellarium
stepmania
stoplight-studio
storyboarder
streamlink-twitch-gui
stremio
stretchly
studio-3t
subethaedit
subler
sublime-text
subsync
subtitles
subtools
superduper
surfshark
surge-synthesizer
suspicious-package
svgcleaner
swift-publisher
swifty
swimat
switch
switchhosts
switchresx
synalyze-it-pro
sync
syncmate
syncovery
syncthing
synergy
syntax-highlight
table-tool
tableau
tableflip
tabula
tad
tagger
tagspaces
tap-forms
taskade
taskexplorer
taskpaper
td-agent
teamviewer
telegram-desktop
tempo
tencent-meeting
tenor
termhere
terminus
termius
tex-live-utility
texpad
texshop
texstudio
textexpander
texts
textual
texworks
tg-pro
the-battle-for-wesnoth
the-cheat
the-clock
the-unarchiver
thebrain
thedesk
themeengine
there
therm
thonny-xxl
thor
thought-train
thunder
thunderbird
thyme
tickeys
ticktick
tidal
tidepool-uploader
tiger-trade
tigervnc-viewer
tikzit
tiled
tiles
timche-gmail-desktop
time-lapse-assembler
time-out
time-sink
timecamp
timemachineeditor
timestamp
timing
tinkerwell
tinypng4mac
tip
tipp10
tla-plus-toolbox
tnefs-enough
todometer
todour
toggl-track
toolreleases
torguard
tortoisehg
tower
trader-workstation
trailer
tranquility
transmission
transmission-nightly
transmit
transnomino
transocks
trash-it
treesheets
tribler
trilium-notes
trinity
triplecheese
trolcommander
tropy
trufont
tunnelbear
tunnelblick-beta
tusk
tuxera-ntfs
tv-browser
tvrenamer
tweet-tray
tweetbot
tweeten
twine
typeface
typinator
typora
tysimulator
ubar
udeler
ueli
ultimaker-cura
unclutter
uncolored
uncrustifyx
unetbootin
uninstallpkg
unison
universal-media-server
unlox
unpkg
unshaky
upic
upterm
usage
usenapp
utox
v2rayu
v2rayx
valentina-studio
valley
vanilla
vassal
vcv-rack
vellum
veonim
veracrypt
veusz
viber
vidrio
vienna
vimr
virtualhere
viscosity
visit
visual-paradigm
visual-paradigm-ce
visual-studio
visual-studio-code
visual-studio-code-insiders
vivaldi
vk-messenger
vlc
vlc-nightly
vmware-fusion
vmware-horizon-client
vnc-viewer
vnote
voov-meeting
vorta
vox
vscodium
vsee
vuescan
vuze
vv
wail
wallpaper-wizard
warzone-2100
wasabi-wallet
waterfox-current
waves-central
wavtap
webcatalog
webpack-dashboard
webstorm
webtorrent
wechat
wewechat
wey
whale
whalebird
whatroute
whatsapp
whatsize
whatsyoursign
whichspace
whoozle-android-file-transfer
wifi-explorer
winclone
winds
windscribe
wingpersonal
wintertime
wire
wireshark
wjoy
wondershare-uniconverter
wordpresscom
wordservice
workbench
workflowy
workplace-chat
wormhole
wpsoffice
writer
wwdc
xact
xamarin-workbooks
xbench
xca
xcodeclangformat
xee
xit
xld
xmind
xmind-zen
xnconvert
xnviewmp
xquartz
xscope
yacreader
yakyak
yam-display
yandex
yandex-disk
yate
yep
yinxiangbiji
yo
yoda
youdaonote
youku
youll-never-take-me-alive
youtube-to-mp3
yt-music
ytmdesktop-youtube-music
zazu
zeebe-modeler
zenmap
zettlr
zoc
zoomin
zoomus
zotero
zterm
zulip
zxpinstaller
==> Deleted Casks
little-snitch-nightly
pext-nightly
station

Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
Warning: asdf 0.8.0 already installed
Warning: bat 0.15.4 already installed
Warning: fzf 0.22.0 already installed
Warning: gh 0.12.0 already installed
Warning: git 2.28.0 already installed
Warning: heroku/brew/heroku 7.42.13 already installed
Warning: artsy/formulas/hokusai 0.5.11 already installed
Warning: httpie 2.2.0 already installed
Warning: hub 2.14.2 already installed
Warning: macvim 8.2-165_1 already installed
Warning: the_silver_searcher 2.2.0 already installed
Warning: tmux 3.1b already installed
Warning: yarn 1.22.5 already installed
Warning: zsh-completions 0.32.0 already installed
+ asdf plugin-update --all
Updating nodejs...
From https://github.com/asdf-vm/asdf-nodejs
   cd8dc32..de91346  master     -> master
   cd8dc32..de91346  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating python...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby...
Already on 'master'
Your branch is up to date with 'origin/master'.
+ asdf reshim
+ gem update --system
Latest version already installed. Done.
+ npm install --global npm
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npm -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npm-cli.js
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npx -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npx-cli.js

> npm@6.14.8 postinstall /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm
> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/.hooks/postinstall
+ npm@6.14.8
updated 1 package in 4.349s
+ nuke_modules
/Users/jon/code/metaphysics/node_modules
/Users/jon/code/eigen/node_modules
/Users/jon/code/peril-settings/node_modules
1.5G cleaned up

```

</details>

## replug.log

<details>

```
+ PlugClean
Searching for invalid plugins in /Users/jon/.vim/plugs
[==========================================================]

Already clean.
+ PlugInstall
Updated. Elapsed time: 0.704495 sec.
[=========================================================]

- Finishing ... Done!
- bufkill.vim: Already installed
- fzf: Already installed
- vim-hashrocket: Already installed
- vim-rake: Already installed
- vim-turbux: Already installed
- vim-pug: Already installed
- vim-ruby: Already installed
- vim-textobj-user: Already installed
- vim-scriptease: Already installed
- vim-rsi: Already installed
- tslime.vim: Already installed
- vim-vividchalk: Already installed
- vim-coffee-script: Already installed
- vim-graphql: Already installed
- vim-rhubarb: Already installed
- vim-markdown: Already installed
- pgsql.vim: Already installed
- vim-vinegar: Already installed
- vim-slim: Already installed
- vim-repeat: Already installed
- vim-git: Already installed
- vim-commentary: Already installed
- vim-blockle: Already installed
- vim-endwise: Already installed
- supertab: Already installed
- vim-sleuth: Already installed
- ack.vim: Already installed
- vim-spacejam: Already installed
- bufexplorer.zip: Already installed
- vim-sensible: Already installed
- vim-unimpaired: Already installed
- vim-headfirst: Already installed
- vim-json: Already installed
- vim-bdubs: Already installed
- vim-rails: Already installed
- vim-weefactor: Already installed
- vim-eunuch: Already installed
- vim-railscasts: Already installed
- gitv: Already installed
- vim-irblack: Already installed
- vim-fugitive: Already installed
- vim-textobj-rubyblock: Already installed
- tabular: Already installed
- vim-speeddating: Already installed
- ale: Already installed
- vim-bundler: Already installed
- vim-haml: Already installed
- splitjoin.vim: Already installed
- vim-jsx: Already installed
- vim-abolish: Already installed
- vim-ragtag: Already installed
- vim-projectionist: Already installed
- vim-surround: Already installed
- typescript-vim: Already installed
- vim-javascript: Already installed
- vim-cucumber: Already installed
- vim-styled-components: Already installed
+ PlugUpdate
Updated. Elapsed time: 4.484695 sec.
[=======================================================xx]

- Finishing ... Done!
x tslime.vim:
    merge: origin/master - not something we can merge
x vim-turbux:
    merge: origin/master - not something we can merge
- bufkill.vim: Already up to date.
- fzf:  3 files changed, 21 insertions(+), 9 deletions(-)
- vim-hashrocket: Already up to date.
- vim-rake: Already up to date.
- vim-pug: Already up to date.
- vim-ruby: Already up to date.
- vim-textobj-user: Already up to date.
- vim-scriptease: Already up to date.
- vim-rsi: Already up to date.
- vim-vividchalk: Already up to date.
- vim-coffee-script: Already up to date.
- vim-graphql:  rename test/reason/{vim-reasonml.vader => default.vader} (100%)
- vim-rhubarb: Already up to date.
- vim-markdown: Already up to date.
- pgsql.vim: Already up to date.
- vim-vinegar: Already up to date.
- vim-slim: Already up to date.
- vim-repeat: Already up to date.
- vim-git: Already up to date.
- vim-commentary: Already up to date.
- vim-blockle: Already up to date.
- vim-endwise: Already up to date.
- supertab: Already up to date.
- vim-sleuth: Already up to date.
- ack.vim: Already up to date.
- vim-spacejam: Already up to date.
- bufexplorer.zip: Already up to date.
- vim-sensible: Already up to date.
- vim-unimpaired: Already up to date.
- vim-headfirst: Already up to date.
- vim-json: Already up to date.
- vim-bdubs: Already up to date.
- vim-rails:  1 file changed, 6 insertions(+), 1 deletion(-)
- vim-weefactor: Already up to date.
- vim-eunuch: Already up to date.
- vim-railscasts: Already up to date.
- gitv: Already up to date.
- vim-irblack: Already up to date.
- vim-fugitive: Already up to date.
- vim-textobj-rubyblock: Already up to date.
- tabular: Already up to date.
- vim-speeddating: Already up to date.
- ale:  create mode 100644 test/test_ale_lint_stop_command.vader
- vim-bundler: Already up to date.
- vim-haml: Already up to date.
- splitjoin.vim: Already up to date.
- vim-jsx: Already up to date.
- vim-abolish: Already up to date.
- vim-ragtag: Already up to date.
- vim-projectionist: Already up to date.
- vim-surround: Already up to date.
- typescript-vim:  1 file changed, 7 insertions(+), 5 deletions(-)
- vim-javascript: Already up to date.
- vim-cucumber: Already up to date.
- vim-styled-components: Already up to date.
+ PlugDiff
5 plugin(s) updated.
[=========================================================]

Last update:
------------

- ale:
  * 08295ce (tag: v3.0.0) Bump the ALE version to 3.0.0 (6 days ago)
  * 4ddf742 Close #2522 - Check pylint on the fly (6 days ago)
  * 78fa93b Add tests for covering the coming Vint version (6 days ago)
  *   62fd83f Merge pull request #3108 from timbedard/vint-add-stdin (6 days ago)
  |\
  | * b800d24 add stdin option for supported vint versions (6 months ago)
  * 6a367e4 Close #3003 - Show ignored linters in :ALEInfo (7 days ago)
  * 7d90ff5 Close #3333 - Add an ALECompletePost event (7 days ago)

- fzf:
  * c60ed17 [vim] Change the default layout to use popup window (3 days ago)

- typescript-vim:
  *   9f247d7 Merge pull request #179 from z0rzi/patch-1 (7 days ago)
  |\
  | * 1557953 exclamation character wrong group (7 months ago)
  *   90405bb Merge pull request #180 from nornagon/patch-1 (7 days ago)
  |\
  | * bf5bddd fix: support all legal regex flags (4 weeks ago)
  * 7586ba2 Merge pull request #181 from patstockwell/extend-global-objects (7 days ago)
  * b5b8641 Extend global objects with js and node keywords (8 days ago)

- vim-graphql:
  * b06a6e6 Skip comments and strings when matching brackets (2 days ago)
  * b4465b9 Use '==#' (instead of 'is#') to compare strings (2 days ago)
  * c032702 Nicer graphqlExtensionPoint syntax highlighting (6 days ago)
  * cd9136b Rename basic Reason syntax test (6 days ago)
  * 9f9aa8b Rename Reason region to graphqlExtensionPoint (6 days ago)

- vim-rails:
  * 3cc3430 Parse :Rails notes like :Rake notes (18 hours ago)

+ PlugUpgrade
+ replug done

```

</details>
