### ISSUE TITLE
Week 39 - juggernaut

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#196]
## Terminal Stuff

* [x] `$ brew upgrade bat fzf git heroku hokusai hub macvim the_silver_searcher tmux yarn`
* [x] `$ replug`
* [x] `$ asdf update && asdf plugin-update --all && asdf reshim`
* [x] `$ gem update --system`
* [x] `$ npm install -g npm`
* [x] `$ nuke_modules`

## Filesystem Housekeeping

* [x] cleanup desktop
* [x] cleanup screenshots
* [x] cleanup screen captures
* [x] cleanup downloads
* [x] empty trash

## Check for Updates

* [x] Alfred
* [x] iTerm2
* [x] 1Password
* [x] Figma
* [x] [Xcode][]
* [x] do App Store.app updates
* [x] do System Updates

## Stay in Sync

* [x] push/pull changes on dotfiles
* [x] push/pull changes on notes
* [x] push/pull changes on secrets
* [x] update list of Artsy repos

## Finishing Up

* [x] check free disk space
* [x] verify last backup on time machine
* [ ] verify last backup on backblaze
* [x] reboot

[Xcode]: https://developer.apple.com/download/more/

**Comment by jonallured** [comment]
## sharpen.log

<details>

```
+ brew upgrade asdf bat fzf gh git heroku hokusai httpie hub macvim the_silver_searcher tmux yarn zsh-completions
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 6 taps (heroku/brew, thoughtbot/formulae, homebrew/cask-versions, homebrew/core, homebrew/cask and artsy/formulas).
==> New Formulae
rustscan
==> Updated Formulae
Updated 346 formulae.
==> Renamed Formulae
gst-validate -> gst-devtools
==> New Casks
anka-build-cloud-registry
anka-virtualization
archi
cernbox
copytranslator
ditto
home-assistant
jetbrains-space
multi
nova
parallels15
vmware-fusion11
==> Updated Casks
1password-beta
1password-cli
4k-video-downloader
4k-youtube-to-mp3
a-better-finder-rename
activedock
adoptopenjdk
affinity-designer-beta
affinity-photo-beta
agenda
aircall
ajour
altair-graphql-client
amazon-chime
amazon-workspaces
android-studio-preview-canary
apache-couchdb
apparency
appcode
atext
avocode
banktivity
bingpaper
bisq
bitwarden
blizz
blueharvest
brave-browser
brave-browser-beta
brave-browser-dev
bricklink-studio
browserosaurus
camtasia
cellprofiler
checkra1n
chromium
chronosync
clash-for-windows
cleanmymac
clickup
clion
clockify
cloudflare-warp
commander-one
cyberduck
cytoscape
dashlane
datagrip
datovka
dbeaver-community
deezer
difffork
discord-canary
disk-drill
diskcatalogmaker
djay-pro
docker-edge
doly
downie
drawio
dropbox-beta
dropbox-passwords
easyeda
eclipse-cpp
eclipse-dsl
eclipse-ide
eclipse-installer
eclipse-java
eclipse-javascript
eclipse-jee
eclipse-modeling
eclipse-php
eclipse-platform
eclipse-rcp
eclipse-testing
electron
element
epic-games
epichrome
eudic
expressvpn
farrago
feed-the-beast
firefox
flipper
flutter
fontexplorer-x-pro
freedom
frhelper
garagebuy
gemini
geneious-prime
geogebra
gns3
godot
goland
goodsync
google-chrome
grids
hammerspoon
hookshot
icollections
icons8
iexplorer
inkdrop
insomnia
insomnia-designer
intellij-idea
intellij-idea-ce
ipe
ipepresenter
iterm2-beta
jabt-flow
jalview
jami
jamulus
java6
jaxx-liberty
joplin
juicebar
kext-updater
keysmith
kite
kitematic
klayout
krisp
kubernetic
lando
lastpass
latexdraw
launchbar
ledger-live
lens
lightproxy
line-bot-designer
loaf
loom
macdive
macgamestore
mactex
mactex-no-gui
macvim
manictime
marvel
marvin
master-password
master-pdf-editor
meetingbar
megasync
melodics
memory
mendeley-reference-manager
metabase
metasploit
microsoft-auto-update
microsoft-edge
microsoft-edge-beta
microsoft-edge-dev
microsoft-excel
microsoft-office
microsoft-outlook
microsoft-powerpoint
microsoft-word
milanote
minecraft-server
missive
mockoon
moneymoney
mongodb-compass
mongodb-compass-isolated-edition
mongodb-compass-readonly
monitorcontrol
mono-mdk-for-visual-studio
mountain-duck
mycrypto
navicat-data-modeler
navicat-data-modeler-essentials
navicat-for-mariadb
navicat-for-mysql
navicat-for-oracle
navicat-for-postgresql
navicat-for-sql-server
navicat-for-sqlite
navicat-premium
navicat-premium-essentials
netnewswire
netron
obsidian
odrive
omnigraffle
opera
opera-developer
osquery
p4v
parallels
parallels-client
pcoipclient
permute
pgadmin4
plex
postbox
pppc-utility
praat
prepros
proclaim
progressive-downloader
proxyman
pycharm
pycharm-ce
pycharm-ce-with-anaconda-plugin
pycharm-with-anaconda-plugin
pyfa
qobuz
qownnotes
qq
qt-creator
raven-reader
razorsql
react-native-debugger
rectangle
refined-github-safari
remember-the-milk
remote-desktop-manager
remote-desktop-manager-free
renamer
rider
ring
robo-3t
rotato
rubymine
runway
screen
scrutiny
sherlock
shift
sidequest
silentknight
sipgate-softphone
sitebulb
sizzy
skim
spires
springtoolsuite
sqleditor
sqlpro-for-mssql
sqlpro-for-sqlite
stack
stack-stack
swift-publisher
swiftformat-for-xcode
swifty
syncovery
synfigstudio
tableau-prep
tableplus
tagspaces
tastyworks
tempo
tencent-lemon
termius
termius-beta
thebrain
tinymediamanager
toggl-track
tor-browser-alpha
torguard
trailer
transnomino
tunnelbear
typinator
ubersicht
uu-booster
vassal
visual-studio
visual-studio-code
visual-studio-code-insiders
vitamin-r
vmware-fusion
vrew
vscodium
vuescan
webcatalog
webex-teams
wechatwebdevtools
wechatwork
whatroute
whatsapp
wireshark
wondershare-uniconverter
wordpresscom
wrike
xamarin-ios
yed
youdaonote
youku
zalo
zoc
zoom-for-it-admins
zoomus
zulu
==> Deleted Casks
anka-flow
chicken
java
java11

Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
Warning: asdf 0.8.0 already installed
Warning: bat 0.15.4 already installed
Warning: fzf 0.22.0 already installed
Warning: git 2.28.0 already installed
Warning: artsy/formulas/hokusai 0.5.11 already installed
Warning: httpie 2.2.0 already installed
Warning: hub 2.14.2 already installed
Warning: the_silver_searcher 2.2.0 already installed
Warning: tmux 3.1b already installed
Warning: yarn 1.22.5 already installed
Warning: zsh-completions 0.32.0 already installed
==> Upgrading 3 outdated packages:
gh 0.12.0 -> 1.0.0
heroku/brew/heroku 7.42.13 -> 7.43.1
macvim 8.2-165_1 -> 8.2-166
==> Upgrading gh 0.12.0 -> 1.0.0 
==> Downloading https://homebrew.bintray.com/bottles/gh-1.0.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/77b42bd6b610134ee3b407304a816ddbbcb03a38b527dbd00c25df74a3623606?response-content-disposition=attachment%3Bfilename%3D%22gh-1.0.0.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNzdiNDJiZDZiNjEwMTM0ZWUzYjQwNzMwNGE4MTZkZGJiY2IwM2EzOGI1MjdkYmQwMGMyNWRmNzRhMzYyMzYwNj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdoLTEuMC4wLmNhdGFsaW5hLmJvdHRsZS50YXIuZ3olMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDA3ODk3NTR9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=meAo7JHWG1pdlPqz6ZEI3AdPSFehpFX20dT955uN97zm1DD7i-gwpGPG4N1BfB3-WM8w8YDQeALBjmooBuicBFZWaQ0XfDeofRoHP3eXml2sOddhG3RuM1uJeAdgqeuyhfwgB0Y8Sq71~VBPUjTLM~yNnHPYfcBnnliroQUnpq9RQFjKDh1R~18yee3C0-LSoCAuYq5I4kaut6M6RYnt8JGsw~rWm5cW8JFZb2aVHqc4Zj1XmFhyUOIKl1VpP4qOOmZes-ggra2wFWvrXhhMlXJJiFZOHUoDpsjfDjhED5-q3GSUt4BoimwYatOu7ITRt6dcbA3UCkgaWhvDCWyCLA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring gh-1.0.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/gh/1.0.0: 60 files, 16.2MB
Removing: /usr/local/Cellar/gh/0.12.0... (49 files, 16MB)
Removing: /Users/jon/Library/Caches/Homebrew/gh--0.12.0.catalina.bottle.tar.gz... (5.6MB)
==> Upgrading heroku/brew/heroku 7.42.13 -> 7.43.1 
==> Downloading https://cli-assets.heroku.com/heroku-v7.43.1/heroku-v7.43.1.tar.xz
==> Caveats
To use the Heroku CLI's autocomplete --
  Via homebrew's shell completion:
    1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
        NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
              and called, either explicitly or via a framework like oh-my-zsh.
    2) Then run
      $ heroku autocomplete --refresh-cache

  OR

  Use our standalone setup:
    1) Run and follow the install steps:
      $ heroku autocomplete

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/heroku/7.43.1: 27,475 files, 59.4MB, built in 32 seconds
Removing: /usr/local/Cellar/heroku/7.42.13... (27,404 files, 59.2MB)
Removing: /Users/jon/Library/Caches/Homebrew/heroku--7.42.13.tar.xz... (6.9MB)
==> Upgrading macvim 8.2-165_1 -> 8.2-166 
==> Downloading https://homebrew.bintray.com/bottles/macvim-8.2-166.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/7bf02a4d9bde3ab4a9575e11382ebb7719f1eacc853c6a105c2ffd3fc3489fc5?response-content-disposition=attachment%3Bfilename%3D%22macvim-8.2-166.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvN2JmMDJhNGQ5YmRlM2FiNGE5NTc1ZTExMzgyZWJiNzcxOWYxZWFjYzg1M2M2YTEwNWMyZmZkM2ZjMzQ4OWZjNT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm1hY3ZpbS04LjItMTY2LmNhdGFsaW5hLmJvdHRsZS50YXIuZ3olMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDA3ODk4MDB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=rLo7btL5yROPsvv4wUaxlMOVOpWnXFw080aHz7di9YK~A4-PmOgYXGNt-gZW5afwafgy5uTxdgPGFJ0sQEQLEaTFNm9p4g7S3PxN-N4rbjJk4Y72ub9I1YRQLIFPpa1Xko0q6VlcnNFwjSiBeFL1ZSnqdsSh~CSK3oBxL5kAWwV5NuRAIzii7MJvAJxumnvtSauvIqbzOJaIXMfhGdmRMNg69dhKoojl8KcL6eQMFWjhi2ED-vi~KDbkJaF8HxnD2AXSgsDC6mdwIpOHlFdkirB5cNyBuQm~7j~PHy8Uocx20H1TDu1QP6D3J~iaBTu2phQheoT9SN5Bmz4u6E8FXg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring macvim-8.2-166.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/macvim/8.2-166: 2,358 files, 45.4MB
Removing: /usr/local/Cellar/macvim/8.2-165_1... (2,332 files, 44.9MB)
Removing: /Users/jon/Library/Caches/Homebrew/macvim--8.2-165_1.catalina.bottle.tar.gz... (18MB)
==> Caveats
==> gh
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> heroku
To use the Heroku CLI's autocomplete --
  Via homebrew's shell completion:
    1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
        NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
              and called, either explicitly or via a framework like oh-my-zsh.
    2) Then run
      $ heroku autocomplete --refresh-cache

  OR

  Use our standalone setup:
    1) Run and follow the install steps:
      $ heroku autocomplete

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
+ asdf plugin-update --all
Updating nodejs...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating python...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby...
Already on 'master'
Your branch is up to date with 'origin/master'.
+ asdf reshim
+ gem update --system
Latest version already installed. Done.
+ npm install --global npm
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npm -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npm-cli.js
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npx -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npx-cli.js

> npm@6.14.8 postinstall /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm
> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/.hooks/postinstall
+ npm@6.14.8
updated 1 package in 4.431s
+ nuke_modules
/Users/jon/code/metaphysics/node_modules
450M cleaned up

```

</details>

## replug.log

<details>

```
+ PlugClean
Searching for invalid plugins in /Users/jon/.vim/plugs
[==========================================================]

Already clean.
+ PlugInstall
Updated. Elapsed time: 0.381407 sec.
[=========================================================]

- Finishing ... Done!
- bufkill.vim: Already installed
- fzf: Already installed
- vim-hashrocket: Already installed
- vim-rake: Already installed
- vim-turbux: Already installed
- vim-pug: Already installed
- vim-ruby: Already installed
- vim-textobj-user: Already installed
- vim-scriptease: Already installed
- vim-rsi: Already installed
- tslime.vim: Already installed
- vim-vividchalk: Already installed
- vim-coffee-script: Already installed
- vim-graphql: Already installed
- vim-rhubarb: Already installed
- vim-markdown: Already installed
- pgsql.vim: Already installed
- vim-vinegar: Already installed
- vim-slim: Already installed
- vim-repeat: Already installed
- vim-git: Already installed
- vim-commentary: Already installed
- vim-blockle: Already installed
- vim-endwise: Already installed
- supertab: Already installed
- vim-sleuth: Already installed
- ack.vim: Already installed
- vim-spacejam: Already installed
- bufexplorer.zip: Already installed
- vim-sensible: Already installed
- vim-unimpaired: Already installed
- vim-headfirst: Already installed
- vim-json: Already installed
- vim-bdubs: Already installed
- vim-rails: Already installed
- vim-weefactor: Already installed
- vim-eunuch: Already installed
- vim-railscasts: Already installed
- gitv: Already installed
- vim-irblack: Already installed
- vim-fugitive: Already installed
- vim-textobj-rubyblock: Already installed
- tabular: Already installed
- vim-speeddating: Already installed
- ale: Already installed
- vim-bundler: Already installed
- vim-haml: Already installed
- splitjoin.vim: Already installed
- vim-jsx: Already installed
- vim-abolish: Already installed
- vim-ragtag: Already installed
- vim-projectionist: Already installed
- vim-surround: Already installed
- typescript-vim: Already installed
- vim-javascript: Already installed
- vim-cucumber: Already installed
- vim-styled-components: Already installed
+ PlugUpdate
Updated. Elapsed time: 3.364530 sec.
[=======================================================xx]

- Finishing ... Done!
x tslime.vim:
    merge: origin/master - not something we can merge
x vim-turbux:
    merge: origin/master - not something we can merge
- vim-ruby: Already up to date.
- vim-scriptease: Already up to date.
- vim-textobj-user: Already up to date.
- vim-coffee-script: Already up to date.
- vim-rsi: Already up to date.
- vim-repeat: Already up to date.
- vim-slim: Already up to date.
- vim-vinegar: Already up to date.
- pgsql.vim: Already up to date.
- bufkill.vim: Already up to date.
- vim-markdown: Already up to date.
- fzf: Already up to date.
- vim-graphql: Already up to date.
- vim-hashrocket: Already up to date.
- vim-rake: Already up to date.
- vim-rhubarb: Already up to date.
- vim-git: Already up to date.
- vim-pug: Already up to date.
- vim-commentary: Already up to date.
- supertab: Already up to date.
- vim-endwise: Already up to date.
- vim-blockle: Already up to date.
- vim-sleuth: Already up to date.
- ack.vim: Already up to date.
- vim-vividchalk: Already up to date.
- vim-unimpaired: Already up to date.
- vim-eunuch: Already up to date.
- bufexplorer.zip: Already up to date.
- vim-spacejam: Already up to date.
- vim-rails: Already up to date.
- vim-sensible: Already up to date.
- vim-headfirst: Already up to date.
- vim-bdubs: Already up to date.
- vim-json: Already up to date.
- vim-weefactor: Already up to date.
- vim-fugitive: Already up to date.
- gitv: Already up to date.
- vim-railscasts: Already up to date.
- vim-irblack: Already up to date.
- ale: Already up to date.
- vim-cucumber: Already up to date.
- splitjoin.vim:  1 file changed, 8 insertions(+), 1 deletion(-)
- vim-javascript: Already up to date.
- typescript-vim: Already up to date.
- vim-projectionist: Already up to date.
- vim-textobj-rubyblock: Already up to date.
- tabular: Already up to date.
- vim-speeddating: Already up to date.
- vim-bundler: Already up to date.
- vim-haml: Already up to date.
- vim-jsx: Already up to date.
- vim-abolish: Already up to date.
- vim-ragtag: Already up to date.
- vim-surround: Already up to date.
- vim-styled-components: Already up to date.
+ PlugDiff
1 plugin(s) updated.
[=========================================================]

Last update:
------------

- splitjoin.vim:
  * 7148cbc A note about git submodules (32 hours ago)

+ PlugUpgrade
+ replug done

```

</details>
