### ISSUE TITLE
Week 43 - juggernaut

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#200]
## Terminal Stuff

* [x] `$ brew upgrade bat fzf git heroku hokusai hub macvim the_silver_searcher tmux yarn`
* [x] `$ replug`
* [x] `$ asdf update && asdf plugin-update --all && asdf reshim`
* [x] `$ gem update --system`
* [x] `$ npm install -g npm`
* [x] `$ nuke_modules`

## Filesystem Housekeeping

* [x] cleanup desktop
* [x] cleanup screenshots
* [x] cleanup screen captures
* [x] cleanup downloads
* [x] empty trash

## Check for Updates

* [x] Alfred
* [x] iTerm2
* [x] 1Password
* [x] Figma
* [ ] [Xcode][]
* [x] do App Store.app updates
* [x] do System Updates

## Stay in Sync

* [x] push/pull changes on dotfiles
* [x] push/pull changes on notes
* [x] push/pull changes on secrets
* [x] update list of Artsy repos

## Finishing Up

* [x] check free disk space
* [x] verify last backup on time machine
* [ ] verify last backup on backblaze
* [x] reboot

[Xcode]: https://developer.apple.com/download/more/

**Comment by jonallured** [comment]
## sharpen.log

<details>

```
+ brew upgrade asdf awscli bat fzf gh git heroku hokusai httpie hub jo jq macvim the_silver_searcher tmux yarn zsh-completions
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and mongodb/brew).
==> New Formulae
blaze
cvs-fast-export
device-mapper
foreman
fpart
gcalcli
googletest
gost
libdrm
or-tools
postgresql@12
zsh-you-should-use
==> Updated Formulae
Updated 319 formulae.
==> Deleted Formulae
meson-internal
==> New Casks
displays
gactions
mechvibes
messenger
modern-csv
mongodb-realm-studio
perimeter81
s3stat-setup
==> Updated Casks
5kplayer
affinity-designer-beta
airy
alt-tab
amazon-music
appcleaner
appcode-eap
appgate-sdp-client
atom
atom-beta
audiobook-builder
audirvana
azure-data-studio
bbedit
birdfont
blizz
blocs
blueharvest
bluejeans
bookmacster
boom-3d
boxcryptor
brave-browser
brave-browser-beta
brave-browser-dev
btcpayserver-vault
butt
cacher
calibre
camtasia
camunda-modeler
caprine
carbon-copy-cloner
cellprofiler
chatty
chiaki
chirp
chromedriver-beta
chromium
cleanshot
coda
cookie
copyq
corretto
coteditor
crossover
cycling74-max
dash
dashcam-viewer
data-science-studio
datadog-agent
datovka
dbeaver-community
dcp-o-matic
dcp-o-matic-batch-converter
dcp-o-matic-encode-server
dcp-o-matic-kdm-creator
dcp-o-matic-player
deeper
deezer
djay-pro
docker-edge
dotnet
dotnet-sdk
drama
dropbox-beta
easy-move-plus-resize
electrum
eloston-chromium
emclient
epic-games
epichrome
eset-cyber-security-pro
evernote
expandrive
expressvpn
extraterm
fantastical
farrago
feishu
fing
firefox
flash-npapi
flash-player
flash-player-debugger
flash-player-debugger-npapi
flash-player-debugger-ppapi
flash-ppapi
fldigi
flutter
folding-at-home
folx
framer
freeyourmusic
futuniuniu
geekbench
gemini
get-backup-pro
get-iplayer-automator
ghost-browser
gisto
github-beta
gloomhaven-helper
goodsync
graphicconverter
hackintool
hands-off
hbuilderx
home-assistant
hstracker
ibackup-viewer
icab
icollections
iina-plus
imazing
integrity
intune-company-portal
invisor-lite
iterm2-beta
jamf-migrator
jasp
java-beta
jclasslib-bytecode-viewer
keep-it
kext-updater
keymanager
keysmith
kite
krita
kui
lando-edge
lark
lazpaint
lbry
ledger-live
lehreroffice
lifesize
listen1
local
logisim-evolution
logitech-presentation
logos
loom
lrtimelapse
macx-dvd-ripper-pro
maltego
mamp
mars
masterway-note
mathpix-snipping-tool
mattermost
mcgimp
megasync
melodics
mendeley-reference-manager
microsoft-auto-update
microsoft-edge
microsoft-edge-beta
microsoft-edge-dev
microsoft-excel
microsoft-office
microsoft-outlook
microsoft-powerpoint
microsoft-teams
microsoft-word
milanote
minitube
mochi
monero-wallet
mongodb-compass-beta
mono-mdk
movist-pro
mqttx
mtgaprotracker
multi
musescore
musictube
mymonero
mysqlworkbench
native-access
naver-whale
navicat-premium
netron
noxappplayer
numi
obsidian
odrive
omniplan
onlyoffice
opencpn
openphone
openvpn-connect
opera
opera-beta
opera-developer
oscar
osu-development
paw
pd-l2ork
pdf-expert
pgadmin4
phocus
phpstorm
plex-media-server
plexamp
pocket-casts
polar-bookshelf
popo
porting-kit
praat
presentation
proclaim
profind
protonvpn
protopie
proxyman
pyfa
pyzo
qbittorrent
qobuz
qownnotes
qtum
quickhash
quip
qutebrowser
raven-reader
razorsql
react-studio
rectangle
refined-github-safari
rekordbox
removebg
rescuetime
responsively
reunion
rocket-chat
sabnzbd
scihubeva
seamonkey
second-life-viewer
segger-embedded-studio-for-arm
sequel-ace
sf-symbols
sidequest
signal
signal-beta
sim-genie
sip
sizzy
skype
slack
slack-beta
soulver
spamsieve
spatterlight
spires
splashtop-streamer
splayer
splice
standard-notes
stats
steermouse
strawberry
studio-3t
subler
suspicious-package
swiftformat-for-xcode
swiftstack-client
swinsian
syncovery
syncroom
tastyworks
telavox-flow
tempo
tg-pro
thebrain
thor
thorium
thunderbird
tiger-trade
timer
timeular
toggl-track
tor-browser
trilium-notes
tuple
tweetbot
tweeten
ubersicht
ueli
unity
unity-android-support-for-editor
unity-download-assistant
unity-ios-support-for-editor
unity-lumin-support-for-editor
unity-webgl-support-for-editor
unity-windows-support-for-editor
usenapp
utools
vassal
visicut
visual-studio-code
visual-studio-code-insiders
vivaldi
vivi
vscodium
weakauras-companion
webcatalog
webviewscreensaver
wechat
workflowy
wormhole
yandex-disk
yate
youku
zalo
zoc
zotero
==> Deleted Casks
delta
megahertz-knotes
realm-studio

Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
Warning: asdf 0.8.0 already installed
Warning: bat 0.16.0 already installed
Warning: fzf 0.23.1 already installed
Warning: gh 1.1.0 already installed
Warning: heroku/brew/heroku 7.46.0 already installed
Warning: artsy/formulas/hokusai 0.5.11 already installed
Warning: httpie 2.2.0_1 already installed
Warning: hub 2.14.2 already installed
Warning: jo 1.4 already installed
Warning: jq 1.6 already installed
Warning: macvim 8.2-166_1 already installed
Warning: the_silver_searcher 2.2.0 already installed
Warning: tmux 3.1b already installed
Warning: yarn 1.22.10 already installed
Warning: zsh-completions 0.32.0 already installed
==> Upgrading 2 outdated packages:
awscli 2.0.56 -> 2.0.57
git 2.28.0 -> 2.29.0
==> Upgrading awscli 2.0.56 -> 2.0.57 
==> Downloading https://homebrew.bintray.com/bottles/awscli-2.0.57.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/a7f2553bf36b3138af2ea3861baa22224fbfbb88481182488e9cb23693dd5454?response-content-disposition=attachment%3Bfilename%3D%22awscli-2.0.57.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYTdmMjU1M2JmMzZiMzEzOGFmMmVhMzg2MWJhYTIyMjI0ZmJmYmI4ODQ4MTE4MjQ4OGU5Y2IyMzY5M2RkNTQ1ND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF3c2NsaS0yLjAuNTcuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwMzIwNjk1Nn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=ljdQaQhO37EN6iKO~UVRr6t33A0HfYG7dIULUiVKhs4t3L-6MSZtPmubM8YmFqgL7gvw-Mojjs8LoySYmNunhDv~Vg5ZCS7zNsI2WHJzrgMwiE1udyRh4Mja8kkXO8UGhIqy1Bi0pL7EmmbezR~WM8yrJWL3HuxfcQoKIkTlNxvGsfZXmuufigfcFPf~uVw6p25rY-A~nnNQ0yUj51pZB8eiX0jknfLDHo70I0R5jDDtKDkovY88~WyzQeY06w4-64GwMLrVV5fC0kgKKsqdj6GqxkoUYUpzAKYmCayFSHXtPwF9SLD-D37JikffYxdt46Z2Oblds~M0xLPT29pS2Q__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring awscli-2.0.57.catalina.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/2.0.57: 11,536 files, 82.2MB
Removing: /usr/local/Cellar/awscli/2.0.56... (11,997 files, 86.7MB)
Removing: /Users/jon/Library/Caches/Homebrew/awscli--2.0.56.catalina.bottle.tar.gz... (21.8MB)
==> Upgrading git 2.28.0 -> 2.29.0 
==> Downloading https://homebrew.bintray.com/bottles/git-2.29.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ec73f2ef4364451a8bffef7af1f4f2fbb53145135ea6b9e595ce181bb7567314?response-content-disposition=attachment%3Bfilename%3D%22git-2.29.0.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZWM3M2YyZWY0MzY0NDUxYThiZmZlZjdhZjFmNGYyZmJiNTMxNDUxMzVlYTZiOWU1OTVjZTE4MWJiNzU2NzMxND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdpdC0yLjI5LjAuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwMzIwNjk3Nn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=Rb1dafbskzafOWnxiEx8sk7LdaoTt3GOaMB8KS-iia7OxskfFshHdpnYoV3eKJhjMmO5xlkI6aEJVF7VIfX-GUY7IzA2j6KjlS5qFRf60WOI3Jwmcmz4nfaJgUo2iQBMYx-4kM-EaCSz-nMSLmp60srx8xYyXMeXaPBFiSWdZ3YAGr1WfHJfb1ZdS~AxnGgLWf7~C5xKJ9tof6ppjrmkVFoJK3JFU4wRxcNH7dzNoTlZs4l1GnzFrQUK03k1A11eWoWamKJIqAcu3xRIP0poG1ku9hgMarYaR0I5eli7DI9JF8EZcpvh2zretHzdvoIiBZC~X5n1GX-PkS5MvuskRQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring git-2.29.0.catalina.bottle.tar.gz
==> Caveats
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.29.0: 1,478 files, 39.7MB
Removing: /usr/local/Cellar/git/2.28.0... (1,482 files, 48.9MB)
Removing: /Users/jon/Library/Caches/Homebrew/git--2.28.0.catalina.bottle.tar.gz... (19.4MB)
==> Caveats
==> awscli
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> git
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
+ asdf plugin-update --all
Updating nodejs...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating python...
From https://github.com/danhper/asdf-python
   b544ac9..6f1b8ac  master     -> master
 * [new tag]         v1.0       -> v1.0
   b544ac9..6f1b8ac  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby...
Already on 'master'
Your branch is up to date with 'origin/master'.
+ asdf reshim
+ gem update --system
Latest version already installed. Done.
+ npm install --global npm
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npm -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npm-cli.js
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npx -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npx-cli.js

> npm@6.14.8 postinstall /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm
> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/.hooks/postinstall
+ npm@6.14.8
updated 1 package in 4.944s
+ nuke_modules
/Users/jon/code/reaction/node_modules
/Users/jon/code/metaphysics/node_modules
/Users/jon/code/forty-time-management/typescript/node_modules
/Users/jon/code/eigen/node_modules
/Users/jon/code/force/node_modules
5.4G cleaned up

```

</details>

## replug.log

<details>

```
+ PlugClean
Searching for invalid plugins in /Users/jon/.vim/plugs
[==========================================================]

Already clean.
+ PlugInstall
Updated. Elapsed time: 0.609100 sec.
[=========================================================]

- Finishing ... Done!
- bufkill.vim: Already installed
- fzf: Already installed
- vim-hashrocket: Already installed
- vim-rake: Already installed
- vim-turbux: Already installed
- vim-pug: Already installed
- vim-ruby: Already installed
- vim-textobj-user: Already installed
- vim-scriptease: Already installed
- vim-rsi: Already installed
- tslime.vim: Already installed
- vim-vividchalk: Already installed
- vim-coffee-script: Already installed
- vim-graphql: Already installed
- vim-rhubarb: Already installed
- vim-markdown: Already installed
- pgsql.vim: Already installed
- vim-vinegar: Already installed
- vim-slim: Already installed
- vim-repeat: Already installed
- vim-git: Already installed
- vim-commentary: Already installed
- vim-blockle: Already installed
- vim-endwise: Already installed
- supertab: Already installed
- vim-sleuth: Already installed
- ack.vim: Already installed
- vim-spacejam: Already installed
- bufexplorer.zip: Already installed
- vim-sensible: Already installed
- vim-unimpaired: Already installed
- vim-headfirst: Already installed
- vim-json: Already installed
- vim-bdubs: Already installed
- vim-rails: Already installed
- vim-weefactor: Already installed
- vim-eunuch: Already installed
- vim-railscasts: Already installed
- gitv: Already installed
- vim-irblack: Already installed
- vim-fugitive: Already installed
- vim-textobj-rubyblock: Already installed
- tabular: Already installed
- vim-speeddating: Already installed
- ale: Already installed
- vim-bundler: Already installed
- vim-haml: Already installed
- splitjoin.vim: Already installed
- vim-jsx: Already installed
- vim-abolish: Already installed
- vim-ragtag: Already installed
- vim-projectionist: Already installed
- vim-surround: Already installed
- typescript-vim: Already installed
- vim-javascript: Already installed
- vim-cucumber: Already installed
- vim-styled-components: Already installed
+ PlugUpdate
Updated. Elapsed time: 4.864228 sec.
[=======================================================xx]

- Finishing ... Done!
x tslime.vim:
    merge: origin/master - not something we can merge
x vim-turbux:
    merge: origin/master - not something we can merge
- bufkill.vim: Already up to date.
- fzf:  11 files changed, 317 insertions(+), 157 deletions(-)
- vim-hashrocket: Already up to date.
- vim-rake: Already up to date.
- vim-pug: Already up to date.
- vim-ruby: Already up to date.
- vim-textobj-user: Already up to date.
- vim-scriptease: Already up to date.
- vim-rsi: Already up to date.
- vim-vividchalk: Already up to date.
- vim-coffee-script: Already up to date.
- vim-graphql: Already up to date.
- vim-rhubarb: Already up to date.
- vim-markdown: Already up to date.
- pgsql.vim: Already up to date.
- vim-vinegar: Already up to date.
- vim-slim: Already up to date.
- vim-repeat: Already up to date.
- vim-git: Already up to date.
- vim-commentary: Already up to date.
- vim-blockle: Already up to date.
- vim-endwise: Already up to date.
- supertab: Already up to date.
- vim-sleuth: Already up to date.
- ack.vim: Already up to date.
- vim-spacejam: Already up to date.
- bufexplorer.zip: Already up to date.
- vim-sensible: Already up to date.
- vim-unimpaired: Already up to date.
- vim-headfirst: Already up to date.
- vim-json: Already up to date.
- vim-bdubs: Already up to date.
- vim-rails: Already up to date.
- vim-weefactor: Already up to date.
- vim-eunuch: Already up to date.
- vim-railscasts: Already up to date.
- gitv: Already up to date.
- vim-irblack: Already up to date.
- vim-fugitive: Already up to date.
- vim-textobj-rubyblock: Already up to date.
- tabular: Already up to date.
- vim-speeddating: Already up to date.
- ale:  13 files changed, 124 insertions(+), 81 deletions(-)
- vim-bundler: Already up to date.
- vim-haml: Already up to date.
- splitjoin.vim: Already up to date.
- vim-jsx: Already up to date.
- vim-abolish: Already up to date.
- vim-ragtag: Already up to date.
- vim-projectionist: Already up to date.
- vim-surround: Already up to date.
- typescript-vim: Already up to date.
- vim-javascript: Already up to date.
- vim-cucumber: Already up to date.
- vim-styled-components: Already up to date.
+ PlugDiff
2 plugin(s) updated.
[=========================================================]

Last update:
------------

- ale:
  * 557a1ed Make the two nearly identical Swift tools easier to distinguish (5 days ago)
  * 477eb89 #3332 Implement :ALERename! for ignoring errors (5 days ago)
  * f384d61 Fix sorting of supported tools (5 days ago)

- fzf:
  * d2d4d68 Always show the number of selected entries to indicate if --multi is enabled (4 hours ago)
  * faf68db Implement streaming preview window (#2215) (2 days ago)
  * 305896f README-VIM: g:fzf_action doesn't work with custom sink (2 days ago)

+ PlugUpgrade
diff --git a/rcm/vim/autoload/plug.vim b/rcm/vim/autoload/plug.vim
index 9262208..6393d8d 100644
--- a/rcm/vim/autoload/plug.vim
+++ b/rcm/vim/autoload/plug.vim
@@ -1078,7 +1078,7 @@ function! s:checkout(spec)
   let output = s:git_revision(a:spec.dir)
   if !empty(output) && !s:hash_match(sha, s:lines(output)[0])
     let output = s:system(
-          \ 'git fetch --depth 999999 && git checkout '.plug#shellescape(sha).' --', a:spec.dir)
+          \ 'git -c credential.helper= fetch --depth 999999 && git checkout '.plug#shellescape(sha).' --', a:spec.dir)
   endif
   return output
 endfunction
@@ -1846,7 +1846,7 @@ class Plugin(object):
       self.write(Action.UPDATE, self.name, ['Updating ...'])
       callback = functools.partial(self.write, Action.UPDATE, self.name)
       fetch_opt = '--depth 99999999' if self.tag and os.path.isfile(os.path.join(self.args['dir'], '.git/shallow')) else ''
-      cmd = 'git fetch {0} {1} 2>&1'.format(fetch_opt, G_PROGRESS)
+      cmd = 'git -c credential.helper= fetch {0} {1} 2>&1'.format(fetch_opt, G_PROGRESS)
       com = Command(cmd, self.args['dir'], G_TIMEOUT, callback)
       result = com.execute(G_RETRIES)
       self.write(Action.DONE, self.name, result[-1:])
@@ -2154,7 +2154,7 @@ function! s:update_ruby()
                 if pull
                   log.call name, 'Updating ...', :update
                   fetch_opt = (tag && File.exist?(File.join(dir, '.git/shallow'))) ? '--depth 99999999' : ''
-                  bt.call "#{chdir} && git fetch #{fetch_opt} #{progress} 2>&1", name, :update, nil
+                  bt.call "#{chdir} && git -c credential.helper= fetch #{fetch_opt} #{progress} 2>&1", name, :update, nil
                 else
                   [true, skip]
                 end
+ replug done

```

</details>
