### ISSUE TITLE
Week 46 - juggernaut

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#203]
## Terminal Stuff

* [x] `$ brew upgrade bat fzf git heroku hokusai hub macvim the_silver_searcher tmux yarn`
* [x] `$ replug`
* [x] `$ asdf update && asdf plugin-update --all && asdf reshim`
* [x] `$ gem update --system`
* [x] `$ npm install -g npm`
* [x] `$ nuke_modules`

## Filesystem Housekeeping

* [x] cleanup desktop
* [x] cleanup screenshots
* [x] cleanup screen captures
* [x] cleanup downloads
* [x] empty trash

## Check for Updates

* [ ] Alfred
* [ ] iTerm2
* [ ] 1Password
* [ ] Figma
* [ ] [Xcode][]
* [ ] do App Store.app updates
* [ ] do System Updates

## Stay in Sync

* [ ] push/pull changes on dotfiles
* [ ] push/pull changes on notes
* [ ] push/pull changes on secrets
* [ ] update list of Artsy repos

## Finishing Up

* [x] check free disk space
* [x] verify last backup on time machine
* [ ] verify last backup on backblaze
* [x] reboot

[Xcode]: https://developer.apple.com/download/more/

**Comment by jonallured** [comment]
## sharpen.log

<details>

```
+ brew upgrade asdf awscli bat fzf gh git heroku hokusai httpie hub jo jq macvim the_silver_searcher tmux yarn zsh-completions
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
chars
checkov
condure
dog
dotenv-linter
easy-rsa
glab
gosec
isl@0.18
kube-linter
lab
libxp
linux-headers
markdownlint-cli
rm-improved
showkey
strace
tree-sitter
wangle
xbitmaps
xterm
yh
==> Updated Formulae
Updated 392 formulae.
==> New Casks
aleo-studio
deviceinfo
electricbinary
freecad-pre
ibm-aspera-connect
lunar-client
morpheus-beta
obs-websocket
pitch
protoio-overflow
tyme
==> Updated Casks
5kplayer
abstract
acorn
adobe-creative-cloud-cleaner-tool
affinity-designer-beta
airfoil
airparrot
airtable
ajour
alt-tab
altair-graphql-client
android-platform-tools
android-studio-preview-canary
another-redis-desktop-manager
anydo
apparency
appcode
appgate-sdp-client
appstudio
aptible
astropad
astropad-studio
atom-beta
atom-nightly
audio-hijack
audirvana
axure-rp
backblaze-downloader
balenaetcher
banktivity
bartender
battle-net
beatunes
bibdesk
binance
biscuit
blueharvest
bluejeans
bonitastudiocommunity
boost-note
boxcryptor
brave-browser
brave-browser-beta
brave-browser-dev
bricklink-partdesigner
bricklink-studio
brooklyn
burp-suite
busycal
camo-studio
charles
checkra1n
chromium
ckan
clash-for-windows
clashx
cljstyle
clockify
colorsnapper
craftmanager
daedalus-flight
daedalus-mainnet
dbschema
deezer
default-folder-x
discord-canary
displays
drivedx
dropbox-beta
dropbox-passwords
droplr
dropshare
eaglefiler
electerm
electronmail
eloston-chromium
epichrome
eul
evernote
exodus
fantastical
feishu
firefox
fission
fl-studio
flash-npapi
flash-player
flash-player-debugger
flash-player-debugger-npapi
flash-player-debugger-ppapi
flash-ppapi
flightgear
flipper
flock
fontforge
franz
freac
freecad
fsnotes
garagesale
gemini
ghost-browser
gifox
gitfinder
github
gns3
golly
goodsync
google-chrome
google-chrome-beta
google-chrome-dev
google-cloud-sdk
gotomeeting
grandtotal
gzdoom
hackintool
harmony
hazel
hazeover
hiarcs-chess-explorer
hookshot
hstracker
icab
icq
iina
imazing
insync
iridium
istat-menus
iterm2-beta
jabt-flow
jami
joplin
julia
kaleidoscope
keepassxc
keepingyouawake
kext-updater
keyboard-lock
keysmith
kicad
klokki
knime
kodelife
lando-edge
lark
lehreroffice
liclipse
lifesize
lingon-x
loaf
lockrattler
loom
loopback
macdive
macpilot
mactracker
malus
mater
matterhorn
meetingbar
megasync
melodics
memo
mia-for-gmail
microsoft-edge
microsoft-edge-beta
microsoft-edge-dev
microsoft-teams
minishift
minizincide
missive
mochi
modern-csv
monero-wallet
mongodb-compass
mongodb-compass-beta
mongodb-compass-isolated-edition
mongodb-compass-readonly
morpheus
mtgaprotracker
mudlet
multitouch
mumu
musaicfm
netnewswire
netron
network-radar
nightowl
nvidia-geforce-now
obsidian
octoscreen
odrive
openoffice
openvanilla
openvpn-connect
opera
opera-beta
opera-gx
orange
osxfuse
pacifist
pagico
pdf-expert
pdf-expert-beta
pdf-squeezer
piezo
plex
plex-media-server
plexamp
pocket-casts
popo
portfolioperformance
postman
praat
pritunl
profind
protonvpn
protopie
proxyman
pulse-sms
qlcolorcode
qlmarkdown
qownnotes
querious
quip
qv2ray
raindropio
react-studio
refined-github-safari
rescuetime
ridibooks
roboform
rocket-chat
rotato
rstudio-preview
runjs
sage
scratch
segger-embedded-studio-for-arm
sherlock
shift
sia-ui
signal
silentknight
sipgate-softphone
sitebulb
sizzy
slack
slack-beta
slite
snagit
solar2d
sonic-visualiser
soundsource
spires
splice
spotify
stack-stack
standard-notes
stats
steam
streamlabs-obs
stretchly
subethaedit
sublercli
sublime-merge
swiftformat-for-xcode
swifty
swinsian
swish
symboliclinker
tandem
teamspeak-client
techsmith-capture
telegram
telegram-desktop
telegram-desktop-dev
tempo
texmacs
texpad
thingsmacsandboxhelper
thunderbird
tiles
tongbu
touchdesigner
touchosc-bridge
touchosc-editor
tower
tunnelblick
tuple
unetbootin
uninstallpkg
unite
unity
unity-android-support-for-editor
unity-hub
unity-ios-support-for-editor
unity-lumin-support-for-editor
unity-webgl-support-for-editor
unity-windows-support-for-editor
universal-media-server
usb-overdrive
vagrant
vagrant-vmware-utility
vassal
vienna
visual-paradigm
visual-paradigm-ce
visual-studio-code
visual-studio-code-insiders
vivaldi
vrew
vscodium
vuescan
webcatalog
wechatwork
whatsapp
wifi-explorer
wondershare-filmora
workflowy
wormhole
xamarin-ios
xamarin-mac
zeplin
zoc
zoom-for-it-admins
zoomus
zotero
zprint
==> Deleted Casks
aliwangwang
aspera-connect
docear
yandexradio

Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
Warning: asdf 0.8.0 already installed
Warning: bat 0.16.0 already installed
Warning: gh 1.2.0 already installed
Warning: git 2.29.2 already installed
Warning: heroku/brew/heroku 7.47.0 already installed
Warning: artsy/formulas/hokusai 0.5.12 already installed
Warning: httpie 2.3.0 already installed
Warning: hub 2.14.2 already installed
Warning: jo 1.4 already installed
Warning: jq 1.6 already installed
Warning: macvim 8.2-166_1 already installed
Warning: the_silver_searcher 2.2.0 already installed
Warning: yarn 1.22.10 already installed
Warning: zsh-completions 0.32.0 already installed
==> Upgrading 3 outdated packages:
awscli 2.0.61 -> 2.0.63
fzf 0.24.1 -> 0.24.3
tmux 3.1c -> 3.1c_1
==> Upgrading awscli 2.0.61 -> 2.0.63 
==> Downloading https://homebrew.bintray.com/bottles/awscli-2.0.63.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/324d7486b7f6d29b6d5697e059d4bde72bad7c57c1930821178141143cef0432?response-content-disposition=attachment%3Bfilename%3D%22awscli-2.0.63.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMzI0ZDc0ODZiN2Y2ZDI5YjZkNTY5N2UwNTlkNGJkZTcyYmFkN2M1N2MxOTMwODIxMTc4MTQxMTQzY2VmMDQzMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF3c2NsaS0yLjAuNjMuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwNTAyMDk1MH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=ABnTqFT-QVP5MnWKcXxD9MXMb~l2uJPa8PyT7MEOTSVguBHF2nZYmwX3qH2X3n-gw1P7sY~K41U2vtBDSBsJPFIPypvjQ79VXx~4MHsLWL1MDWPfNKis~2ZiIdeLh7i6WgCNaKzGSI2Z~bEa3gvK30rCw4h8PaJmuJxWjfrze-F-3zjdo8ktqM-OwT~YRrGHJwUMUBPfiNVizPtQqD7ueWQqcFPVqP~xHtjXUJgOTQSro72agQj1-Cl1Y-91rBlC5Zto4MC9bc9QozsJQ9yaCbWNBE5CVMptm6Gzaylpfx7CXreTYW5Z7xxT~Po3T8fwkwcBdxcVY4jX0m4P4ORa-Q__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring awscli-2.0.63.catalina.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/2.0.63: 11,644 files, 82.7MB
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /usr/local/Cellar/awscli/2.0.61... (11,536 files, 82.4MB)
Removing: /Users/jon/Library/Caches/Homebrew/awscli--2.0.61.catalina.bottle.tar.gz... (19.3MB)
Removing: /Users/jon/Library/Caches/Homebrew/freetype--2.10.2.catalina.bottle.tar.gz... (893.5KB)
Removing: /Users/jon/Library/Caches/Homebrew/freetype--2.10.3.catalina.bottle.tar.gz... (901.2KB)
Removing: /Users/jon/Library/Caches/Homebrew/fzf--0.24.1.catalina.bottle.tar.gz... (2.0MB)
Removing: /Users/jon/Library/Caches/Homebrew/glib--2.66.1.catalina.bottle.tar.gz... (4.5MB)
Removing: /Users/jon/Library/Caches/Homebrew/httpie--2.3.0.catalina.bottle.tar.gz... (3.4MB)
Removing: /Users/jon/Library/Caches/Homebrew/imagemagick--7.0.10-34.catalina.bottle.tar.gz... (10.0MB)
Removing: /Users/jon/Library/Caches/Homebrew/jasper--2.0.21.catalina.bottle.tar.gz... (655.8KB)
Removing: /Users/jon/Library/Caches/Homebrew/libde265--1.0.7.catalina.bottle.tar.gz... (705KB)
Removing: /Users/jon/Library/Caches/Homebrew/libgcrypt--1.8.6.catalina.bottle.tar.gz... (1MB)
Removing: /usr/local/Cellar/libgpg-error/1.37... (26 files, 879.0KB)
Removing: /usr/local/Cellar/libgpg-error/1.38... (26 files, 921.1KB)
Removing: /usr/local/Cellar/libomp/10.0.1... (9 files, 1.3MB)
Removing: /Users/jon/Library/Caches/Homebrew/libomp--10.0.1.catalina.bottle.tar.gz... (461.0KB)
Removing: /Users/jon/Library/Caches/Homebrew/memcached--1.6.7.catalina.bottle.tar.gz... (120.8KB)
Removing: /Users/jon/Library/Caches/Homebrew/node--14.13.1_1.catalina.bottle.tar.gz... (16.8MB)
Removing: /usr/local/Cellar/openssl@1.1/1.1.1g... (8,059 files, 18MB)
Removing: /usr/local/Cellar/p11-kit/0.23.20... (63 files, 2.9MB)
Removing: /usr/local/Cellar/p11-kit/0.23.20_1... (63 files, 2.9MB)
Removing: /Users/jon/Library/Caches/Homebrew/pango--1.46.2.catalina.bottle.tar.gz... (728KB)
Removing: /Users/jon/Library/Caches/Homebrew/postgresql--12.4.catalina.bottle.tar.gz... (10.8MB)
Removing: /usr/local/Cellar/python@3.9/3.9.0... (4,477 files, 72.7MB)
Removing: /usr/local/Cellar/ruby/2.7.1_2... (20,142 files, 32.2MB)
Removing: /Users/jon/Library/Caches/Homebrew/x265--3.4.catalina.bottle.1.tar.gz... (4.9MB)
Removing: /Users/jon/Library/Caches/Homebrew/portable-ruby-2.6.3_1.yosemite.bottle.tar.gz... (9.1MB)
Removing: /Users/jon/Library/Caches/Homebrew/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz... (9.1MB)
Removing: /Users/jon/Library/Logs/Homebrew/pixman... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/gts... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/pango... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/harfbuzz... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/netpbm... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/awscli... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/graphite2... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/cairo... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/gobject-introspection... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/fribidi... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/fontconfig... (1KB)
Removing: /Users/jon/Library/Logs/Homebrew/graphviz... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/gd... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/bat... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/jasper... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/lzo... (64B)
Removing: /Users/jon/Library/Logs/Homebrew/copy_env... (119B)
Pruned 0 symbolic links and 10 directories from /usr/local
==> Upgrading fzf 0.24.1 -> 0.24.3 
==> Downloading https://homebrew.bintray.com/bottles/fzf-0.24.3.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/76bc4f0d19d68580704b4cf66a57650bcb9a18494b1c61f78770919be3a2b510?response-content-disposition=attachment%3Bfilename%3D%22fzf-0.24.3.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNzZiYzRmMGQxOWQ2ODU4MDcwNGI0Y2Y2NmE1NzY1MGJjYjlhMTg0OTRiMWM2MWY3ODc3MDkxOWJlM2EyYjUxMD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmZ6Zi0wLjI0LjMuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwNTAyMDk4OX0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=TOTXwcco5old2KbaxDLN56XSQbHueOVGMQenFil8vysEoj1zmmcVlW7VrE3okH9djFinERAwb5L56J32mQiap1tYFLihSHBjKT436y9aXBVjzCBjpSdmgYrl7k-TIU9bOy9UMGIt9~OhQgB0fxg5ozoSOiIArOBziUeWXEIfwI-62OVO6~1ymW9DATIti6CRyr7bH3wg3EDJMd~HPQY2Bq5wFzHajvfahGMoghHPCSLFALnG27QQSePktvg1~ILmGC0wIlSKvi26KVJVywLhXfBzU0EQLujpiZBolsm1X2PeNdT~Go0HHqduIHdBam52y3ir-dxpZSsDje8EMqEHWg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring fzf-0.24.3.catalina.bottle.tar.gz
==> Caveats
To install useful keybindings and fuzzy completion:
  /usr/local/opt/fzf/install

To use fzf in Vim, add the following line to your .vimrc:
  set rtp+=/usr/local/opt/fzf
==> Summary
🍺  /usr/local/Cellar/fzf/0.24.3: 17 files, 3.7MB
Removing: /usr/local/Cellar/fzf/0.24.1... (17 files, 3.7MB)
==> Upgrading tmux 3.1c -> 3.1c_1 
==> Downloading https://homebrew.bintray.com/bottles/tmux-3.1c_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/e1148f3043ef1e77e942bc654e6b3867f40401b0ba93e6d44a460467c51e0a3b?response-content-disposition=attachment%3Bfilename%3D%22tmux-3.1c_1.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZTExNDhmMzA0M2VmMWU3N2U5NDJiYzY1NGU2YjM4NjdmNDA0MDFiMGJhOTNlNmQ0NGE0NjA0NjdjNTFlMGEzYj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnRtdXgtMy4xY18xLmNhdGFsaW5hLmJvdHRsZS50YXIuZ3olMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDUwMjA5OTF9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=JS6tSE6ug08EgUoSFOWdaH~g36nZLaf19rZsQlDRGsW3pBdOx7LU63d-ZuN1gCoE0lF-2NeqNzol6rwvpqPT1hDRG829vtIJIXgz92iDg8it2JBr7DtWcTVNOx4gYebqIAkggroKTRq~pTyPxgPuqEkIqPAzmpB-ft-UQAPOgQO6Q9wJL91~A33pMR8ybVDhZiwEB6T4yA3IanWQ210kIEo5TcbH0ia7WSgNZ-FxBaFLNIktX8gIJMhBaL6O9D0c-dMbwNa1lF21FGCEcpQXimArEXvKNd9WzsrrBcbRPr1H9LcMnNMBtgZtccWPdod2oM9DAEI0RiHlx1qWKDro7A__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring tmux-3.1c_1.catalina.bottle.tar.gz
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/tmux/3.1c_1: 9 files, 867.0KB
Removing: /usr/local/Cellar/tmux/3.1c... (9 files, 861.8KB)
==> Caveats
==> awscli
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> fzf
To install useful keybindings and fuzzy completion:
  /usr/local/opt/fzf/install

To use fzf in Vim, add the following line to your .vimrc:
  set rtp+=/usr/local/opt/fzf
==> tmux
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
+ asdf plugin-update --all
Updating nodejs...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating python...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby...
Already on 'master'
Your branch is up to date with 'origin/master'.
+ asdf reshim
+ gem update --system
Latest version already installed. Done.
+ npm install --global npm
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npm -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npm-cli.js
/Users/jon/.asdf/installs/nodejs/10.15.1/.npm/bin/npx -> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm/bin/npx-cli.js

> npm@6.14.8 postinstall /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/npm
> /Users/jon/.asdf/installs/nodejs/10.15.1/.npm/lib/node_modules/.hooks/postinstall
+ npm@6.14.8
updated 1 package in 5.912s
+ nuke_modules
/Users/jon/code/metaphysics/node_modules
/Users/jon/code/eigen/node_modules
/Users/jon/code/force/node_modules
2.5G cleaned up

```

</details>

## replug.log

<details>

```
+ PlugClean
Searching for invalid plugins in /Users/jon/.vim/plugs
[==========================================================]

Already clean.
+ PlugInstall
Updated. Elapsed time: 0.718557 sec.
[=========================================================]

- Finishing ... Done!
- bufkill.vim: Already installed
- fzf: Already installed
- vim-hashrocket: Already installed
- vim-rake: Already installed
- vim-turbux: Already installed
- vim-pug: Already installed
- vim-ruby: Already installed
- vim-textobj-user: Already installed
- vim-scriptease: Already installed
- vim-rsi: Already installed
- tslime.vim: Already installed
- vim-vividchalk: Already installed
- vim-coffee-script: Already installed
- vim-graphql: Already installed
- vim-rhubarb: Already installed
- vim-markdown: Already installed
- pgsql.vim: Already installed
- vim-vinegar: Already installed
- vim-slim: Already installed
- vim-repeat: Already installed
- vim-git: Already installed
- vim-commentary: Already installed
- vim-blockle: Already installed
- vim-endwise: Already installed
- supertab: Already installed
- vim-sleuth: Already installed
- ack.vim: Already installed
- vim-spacejam: Already installed
- bufexplorer.zip: Already installed
- vim-sensible: Already installed
- vim-unimpaired: Already installed
- vim-headfirst: Already installed
- vim-json: Already installed
- vim-bdubs: Already installed
- vim-rails: Already installed
- vim-weefactor: Already installed
- vim-eunuch: Already installed
- vim-railscasts: Already installed
- gitv: Already installed
- vim-irblack: Already installed
- vim-fugitive: Already installed
- vim-textobj-rubyblock: Already installed
- tabular: Already installed
- vim-speeddating: Already installed
- ale: Already installed
- vim-bundler: Already installed
- vim-haml: Already installed
- splitjoin.vim: Already installed
- vim-jsx: Already installed
- vim-abolish: Already installed
- vim-ragtag: Already installed
- vim-projectionist: Already installed
- vim-surround: Already installed
- typescript-vim: Already installed
- vim-javascript: Already installed
- vim-cucumber: Already installed
- vim-styled-components: Already installed
+ PlugUpdate
Updated. Elapsed time: 3.754299 sec.
[=======================================================xx]

- Finishing ... Done!
x tslime.vim:
    merge: origin/master - not something we can merge
x vim-turbux:
    merge: origin/master - not something we can merge
- bufkill.vim: Already up to date.
- fzf:  8 files changed, 93 insertions(+), 28 deletions(-)
- vim-hashrocket: Already up to date.
- vim-rake: Already up to date.
- vim-pug: Already up to date.
- vim-ruby: Already up to date.
- vim-textobj-user: Already up to date.
- vim-scriptease: Already up to date.
- vim-rsi: Already up to date.
- vim-vividchalk: Already up to date.
- vim-coffee-script: Already up to date.
- vim-graphql: Already up to date.
- vim-rhubarb: Already up to date.
- vim-markdown: Already up to date.
- pgsql.vim: Already up to date.
- vim-vinegar: Already up to date.
- vim-slim: Already up to date.
- vim-repeat: Already up to date.
- vim-git: Already up to date.
- vim-commentary: Already up to date.
- vim-blockle: Already up to date.
- vim-endwise: Already up to date.
- supertab: Already up to date.
- vim-sleuth: Already up to date.
- ack.vim: Already up to date.
- vim-spacejam: Already up to date.
- bufexplorer.zip: Already up to date.
- vim-sensible: Already up to date.
- vim-unimpaired: Already up to date.
- vim-headfirst: Already up to date.
- vim-json: Already up to date.
- vim-bdubs: Already up to date.
- vim-rails: Already up to date.
- vim-weefactor: Already up to date.
- vim-eunuch: Already up to date.
- vim-railscasts: Already up to date.
- gitv: Already up to date.
- vim-irblack: Already up to date.
- vim-fugitive: Already up to date.
- vim-textobj-rubyblock: Already up to date.
- tabular: Already up to date.
- vim-speeddating: Already up to date.
- ale:  2 files changed, 16 insertions(+), 15 deletions(-)
- vim-bundler: Already up to date.
- vim-haml: Already up to date.
- splitjoin.vim: Already up to date.
- vim-jsx: Already up to date.
- vim-abolish: Already up to date.
- vim-ragtag: Already up to date.
- vim-projectionist:  1 file changed, 16 insertions(+), 4 deletions(-)
- vim-surround: Already up to date.
- typescript-vim: Already up to date.
- vim-javascript: Already up to date.
- vim-cucumber: Already up to date.
- vim-styled-components: Already up to date.
+ PlugDiff
3 plugin(s) updated.
[=========================================================]

Last update:
------------

- ale:
  * 1ec573b Merge pull request #3427 from lifecrisis/sh-buffer-vars (6 days ago)
  * 31b7a2d Move the test for buffer-local variables (8 days ago)
  * 7363231 Use the proper term for the "#!" line (8 days ago)
  * 6c22936 Remove a noise comment (8 days ago)

- fzf:
  * 722d66e (tag: 0.24.3) 0.24.3 (27 hours ago)
  * f6269f0 Add --padding option (27 hours ago)
  * 520eae8 Remove print statement for debugging (29 hours ago)
  * d099941 [vim] Fix double path separator issue on Windows (5 days ago)
  * e3e76fa (tag: 0.24.2) 0.24.2 (7 days ago)

- vim-projectionist:
  * 0c6967d Use native json_decode() when available (10 days ago)
  * fb142e2 Experimentally allow string values for delegation (6 months ago)

+ PlugUpgrade
+ replug done

```

</details>
