### ISSUE TITLE
Week 20 - juggernaut

### ISSUE THREAD

**Issue by jonallured** [jonallured/dotfiles#222]
## Terminal Stuff

* [x] `$ brew upgrade bat fzf git heroku hokusai hub macvim the_silver_searcher tmux yarn`
* [x] `$ replug`
* [x] `$ asdf update && asdf plugin-update --all && asdf reshim`
* [x] `$ gem update --system`
* [x] `$ npm install -g npm`
* [x] `$ nuke_modules`

## Filesystem Housekeeping

* [x] cleanup desktop
* [x] cleanup screenshots
* [x] cleanup screen captures
* [x] cleanup downloads
* [x] empty trash

## Check for Updates

* [x] Alfred
* [x] iTerm2
* [x] 1Password
* [x] Figma
* [x] Sketch
* [x] [Xcode][]
* [x] do App Store.app updates
* [x] do System Updates

## Stay in Sync

* [x] push/pull changes on dotfiles
* [x] push/pull changes on notes
* [x] push/pull changes on secrets
* [x] update list of Artsy repos

## Finishing Up

* [x] check free disk space
* [x] verify last backup on time machine
* [x] reboot

[Xcode]: https://developer.apple.com/download/more/

**Comment by jonallured** [comment]
## sharpen.log

<details>

```
+ brew upgrade asdf awscli bat fzf gh git heroku hokusai httpie hub jo jq macvim the_silver_searcher tmux yarn zsh-completions
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: Treating macvim as a formula. For the cask, use homebrew/cask/macvim
Warning: asdf 0.8.0_1 already installed
Warning: awscli 2.2.5 already installed
Warning: bat 0.18.1 already installed
Warning: fzf 0.27.0 already installed
Warning: gh 1.9.2 already installed
Warning: git 2.31.1 already installed
Warning: heroku/brew/heroku 7.53.1 already installed
Warning: artsy/formulas/hokusai 0.5.14 already installed
Warning: httpie 2.4.0 already installed
Warning: hub 2.14.2 already installed
Warning: jo 1.4 already installed
Warning: jq 1.6 already installed
Warning: macvim 8.2-171 already installed
Warning: the_silver_searcher 2.2.0 already installed
Warning: tmux 3.2 already installed
Warning: yarn 1.22.10 already installed
Warning: zsh-completions 0.33.0 already installed
+ asdf plugin-update --all
Updating nodejs...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating python...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby...
Already on 'master'
Your branch is up to date with 'origin/master'.
+ asdf reshim
+ gem update --system
Latest version already installed. Done.
+ npm install --global npm

changed 14 packages, and audited 255 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
+ op update
1Password command-line tool 1.9.2.

You're using the latest version.
+ nuke_modules
/Users/jon/code/force/node_modules
1.2G cleaned up

```

</details>

## replug.log

<details>

```
+ PlugClean
Searching for invalid plugins in /Users/jon/.vim/plugs
[==========================================================]

Already clean.
+ PlugInstall
Updated. Elapsed time: 0.402899 sec.
[=========================================================]

- Finishing ... Done!
- bufkill.vim: Already installed
- fzf: Already installed
- vim-hashrocket: Already installed
- vim-rake: Already installed
- vim-turbux: Already installed
- vim-pug: Already installed
- vim-ruby: Already installed
- vim-textobj-user: Already installed
- vim-scriptease: Already installed
- vim-rsi: Already installed
- tslime.vim: Already installed
- vim-vividchalk: Already installed
- vim-coffee-script: Already installed
- vim-graphql: Already installed
- vim-rhubarb: Already installed
- vim-markdown: Already installed
- pgsql.vim: Already installed
- vim-vinegar: Already installed
- vim-slim: Already installed
- vim-repeat: Already installed
- vim-git: Already installed
- vim-commentary: Already installed
- vim-blockle: Already installed
- vim-endwise: Already installed
- supertab: Already installed
- vim-sleuth: Already installed
- ack.vim: Already installed
- vim-spacejam: Already installed
- bufexplorer.zip: Already installed
- vim-sensible: Already installed
- vim-unimpaired: Already installed
- vim-headfirst: Already installed
- vim-json: Already installed
- vim-bdubs: Already installed
- vim-rails: Already installed
- vim-weefactor: Already installed
- vim-eunuch: Already installed
- vim-railscasts: Already installed
- gitv: Already installed
- vim-irblack: Already installed
- vim-fugitive: Already installed
- vim-textobj-rubyblock: Already installed
- tabular: Already installed
- vim-speeddating: Already installed
- ale: Already installed
- vim-bundler: Already installed
- vim-haml: Already installed
- splitjoin.vim: Already installed
- vim-jsx: Already installed
- vim-abolish: Already installed
- vim-ragtag: Already installed
- vim-projectionist: Already installed
- vim-surround: Already installed
- typescript-vim: Already installed
- vim-javascript: Already installed
- vim-cucumber: Already installed
- vim-styled-components: Already installed
+ PlugUpdate
Updated. Elapsed time: 3.817356 sec.
[=======================================================xx]

- Finishing ... Done!
x tslime.vim:
    merge: origin/master - not something we can merge
x vim-turbux:
    merge: origin/master - not something we can merge
- vim-ruby: Already up to date.
- vim-pug: Already up to date.
- vim-textobj-user: Already up to date.
- vim-scriptease: Already up to date.
- vim-rsi: Already up to date.
- vim-coffee-script: Already up to date.
- vim-vividchalk: Already up to date.
- vim-markdown: Already up to date.
- vim-graphql: Already up to date.
- pgsql.vim: Already up to date.
- bufkill.vim: Already up to date.
- vim-vinegar: Already up to date.
- fzf:  6 files changed, 108 insertions(+), 106 deletions(-)
- vim-rhubarb: Already up to date.
- vim-hashrocket: Already up to date.
- vim-slim: Already up to date.
- vim-rake: Already up to date.
- vim-git: Already up to date.
- vim-repeat: Already up to date.
- vim-commentary: Already up to date.
- vim-endwise: Already up to date.
- vim-blockle: Already up to date.
- supertab: Already up to date.
- vim-bdubs: Already up to date.
- vim-unimpaired: Already up to date.
- vim-spacejam: Already up to date.
- vim-sleuth: Already up to date.
- ack.vim: Already up to date.
- vim-weefactor: Already up to date.
- bufexplorer.zip: Already up to date.
- vim-sensible: Already up to date.
- vim-json: Already up to date.
- vim-headfirst: Already up to date.
- vim-rails: Already up to date.
- vim-fugitive:  1 file changed, 1 insertion(+), 1 deletion(-)
- vim-eunuch: Already up to date.
- gitv: Already up to date.
- vim-railscasts: Already up to date.
- vim-irblack: Already up to date.
- vim-styled-components: Already up to date.
- vim-javascript: Already up to date.
- typescript-vim: Already up to date.
- vim-surround: Already up to date.
- vim-projectionist: Already up to date.
- vim-ragtag: Already up to date.
- vim-textobj-rubyblock: Already up to date.
- tabular: Already up to date.
- vim-speeddating: Already up to date.
- ale: Already up to date.
- vim-bundler: Already up to date.
- vim-haml: Already up to date.
- splitjoin.vim: Already up to date.
- vim-jsx: Already up to date.
- vim-abolish: Already up to date.
- vim-cucumber: Already up to date.
+ PlugDiff
2 plugin(s) updated.
[=========================================================]

Last update:
------------

- fzf:
  * 3f75a83 Replace RuneWidth to StringWidth to handle grapheme clusters (4 days ago)

- vim-fugitive:
  * 0868c30 Tighten up diff highlighting (5 days ago)

+ PlugUpgrade
+ replug done

```

</details>
